### ISSUE TITLE
webwxinit api throw an error `1100`

### ISSUE THREAD

**Issue by lsongdev** [goorockey/node-wechat-terminal#1]
https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxinit?r=447457084

Cookie are required : wxuin=364349xxx; webwx_data_ticket=AQbbpcW2815LTqVvUxxx/xxx'

**Comment by goorockey** [comment]
操作系统和node的版本都是怎样的？

**Comment by lsongdev** [comment]
``` bash
➜  node-wechat-terminal git:(master) uname -a
Darwin Lsong-MacBook-Pro-10.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
➜  node-wechat-terminal git:(master) ✗ node -v
v5.0.0
➜  node-wechat-terminal git:(master) ✗ npm -v
3.3.6
➜  node-wechat-terminal git:(master) ✗ ./cli.js
[QR CODE HERE]
info: Scan above qrcode using mobile wechat.
info: Waiting for scan...
info: QRCode is scanned.
{ BaseResponse: { Ret: 1100, ErrMsg: '' },
  Count: 0,
  ContactList: [],
  SyncKey: { Count: 0, List: [] },
  User:
   { Uin: 0,
     UserName: '',
     NickName: '',
     HeadImgUrl: '',
     RemarkName: '',
     PYInitial: '',
     PYQuanPin: '',
     RemarkPYInitial: '',
     RemarkPYQuanPin: '',
     HideInputBarFlag: 0,
     StarFriend: 0,
     Sex: 0,
     Signature: '',
     AppAccountFlag: 0,
     VerifyFlag: 0,
     ContactFlag: 0,
     WebWxPluginSwitch: 0,
     HeadImgFlag: 0,
     SnsFlag: 0 },
  ChatSet: '',
  SKey: '',
  ClientVersion: 0,
  SystemTime: 0,
  GrayScale: 0,
  InviteStartCount: 0,
  MPSubscribeMsgCount: 0,
  MPSubscribeMsgList: [],
  ClickReportInterval: 0 }
error: 1100
```

**Comment by goorockey** [comment]
@song940 fixed in version 0.1.2

**Comment by superinsky** [comment]
Hi @goorockey , I got a error 1100 , base rq url is https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxinit , so not a qq user.

mac os 10.11, node version 4.4.2.

info: Scan above qrcode using mobile wechat.
info: Waiting for scan...
info: QRCode is scanned.
error: Failed to init. Please try again.
error: 1100 

any thoughts , thanks

**Comment by goorockey** [comment]
Hi @superinsky, can you test your problem with branch **Issue-1-wxinit-1100-error** ?

According to ths [js](https://github.com/goorockey/node-wechat-terminal/blob/master/res/wx20160408.js#L2261) of web wechat, I change server domain by difference login redirect url.

**Comment by superinsky** [comment]
Hi @goorockey , nice one! it works for me now on the new branch. thanks again . it is pretty awesome:)

**Comment by goorockey** [comment]
@superinsky, thanks for your help! :)
