### ISSUE TITLE
为什么出来的二维码是乱的呢？

### ISSUE THREAD

**Issue by lpali** [goorockey/node-wechat-terminal#3]
我是在window上面的cmd窗口上运行的。出来的二维码错位。还有其他窗口可以运行么？

这里不能上传图片。

**Comment by lpali** [comment]
![Uploading aaaaaa.jpg…]()

**Comment by goorockey** [comment]
补充截图：

![322a90cb b0fb7b44 73c97256](https://cloud.githubusercontent.com/assets/1220971/11886720/42045466-a568-11e5-922d-b3379f65b6e5.jpg)

**Comment by goorockey** [comment]
fixed. Reinstall make it work.

**Comment by goorockey** [comment]
原因是二维码输出包qrcode-terminal使用unicode输出小二维码，但windows cmd默认字体对unicode支持得不好。解决方法是在window下退化为使用Ascii code

**Comment by lpali** [comment]
ok,可以了。谢谢
