### ISSUE TITLE
可以加上 OS X 系统通知么？还有图片显示？

### ISSUE THREAD

**Issue by alanoy** [goorockey/node-wechat-terminal#5]
如题，没有通知好麻烦。然后 item2 3 已经支持显示图片了

**Comment by goorockey** [comment]
有空会加上，也欢迎pull request哦~ :smile:

**Comment by goorockey** [comment]
master分支已支持系统通知：）

**Comment by goorockey** [comment]
暂时微信web端还不支持显示图片，主要从背后的js和网络通信无法获取图片链接，所以暂时还不能支持显示图片
